### ISSUE TITLE
ImportError: cannot import name 'jitclass' from 'numba'

### ISSUE THREAD

**Issue by iwatobipen** [ireis/PRF#5]
Hi developer,

Thanks for sharing nice code.
I tested example code and got following error.
ImportError: cannot import name 'jitclass' from 'numba'

I could import jitclass from numba.experimental.
Could you please details of numba version which is used in this code.
Thanks,

Taka

**Comment by ireis** [comment]
Hi,

Thanks for the note! I've removed the jitclass import (it was not used)

Thanks,
Itamar

**Comment by iwatobipen** [comment]
Hi Itamar!
Thanks for your commit.
Best,

Taka
